### ISSUE TITLE
after pip genome2json, there is such an error. And  fllowing the usage of genome2json,  the error is command not found.

### ISSUE THREAD

**Issue by amywen1** [gamcil/genome2json#3]
` pip install genome2json`
Collecting genome2json
  Using cached genome2json-0.0.6-py3-none-any.whl (12 kB)
Installing collected packages: genome2json
Successfully installed genome2json-0.0.6
`python`
Python 3.8.3 (default, May 19 2020, 18:47:26)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import genome2json
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'genome2json'

` Genome2JSON`
-bash: Genome2JSON: command not found

**Comment by gamcil** [comment]
Looks like I need to update my readme :)

The package actually uses the name g2j for imports and the command line interface, so try:

Python: `import g2j`
bash: `g2j -h`
